# Classification of Stress from Physiological data

In [1]:
%matplotlib widget
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.figure as figure
import pandas as pd
from datetime import datetime

from IPython.display import display

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.svm import LinearSVC, SVR, SVC
from sklearn.metrics import ConfusionMatrixDisplay

from sklearn2pmml import sklearn2pmml, PMMLPipeline

from make_classification import avg_res, make_nclassif_random_splits

BASE_PATH = "../../stressid-dataset"
LABELS_SEPARATOR = ","
LABELS_FILENAME = "labels.csv"
FEATURES_SEPARATOR = ","
FEATURES_DIRECTORY = "../Reprod-Features-NK"
FEATURES_FILENAME = f"{FEATURES_DIRECTORY}/ecg_eda_features.csv"
#FEATURES_FILENAME = f"{FEATURES_DIRECTORY}/all_physiological_features.csv"
RESULTS_SEPARATOR = ";"
RESULTS_DIRECTORY = "../stressID/Classification/Results"
BIN_LABELS = ["NoStress", "Stress"]
TER_LABELS = ["Relaxed", "Stress", "RealStress"]
QAD_LABELS = ["Relaxed", "Stress", "RealStress", "Amused"]
DEBUG = True

In [2]:
def make_results_filename(classification: str, splits: int, feature_selection: str | None, test_size: float, state_int: int) -> str:
    now = datetime.now()
    timestamp = now.strftime("%Y%m%d-%H%M%S")
    feature_selection = feature_selection if feature_selection is not None else "None"
    return f"{BASE_PATH}/{RESULTS_DIRECTORY}/{timestamp}_{classification}_{splits}s&{test_size}_{feature_selection}f.{state_int}"

def show_label_stats(labels: list[str], y: pd.Series):
    display(pd.DataFrame(
        {
            "labels": labels,
            "counts": y.value_counts().to_list(),
            "percentage": (y.value_counts(normalize=True) * 100).to_list(),
        }
    ))

def output(results: pd.DataFrame, conf_matrices: np.ndarray, classifiers: list, meta: dict):
    classification = meta['classification']
    n_splits = meta['n_splits']
    feature_selector = meta['feature_selector']
    test_size = meta['test_size']
    state_int = meta['state_int']
    labels = meta['classes']
    averages = avg_res(results)
    if meta['save_results']:
        res_file = make_results_filename(classification, n_splits, feature_selector, test_size, state_int) + ".csv"
        avg_file = make_results_filename(classification, n_splits, feature_selector, test_size, state_int) + ".avg.csv"
        print(f"Saving results to {res_file} and {avg_file}")
        results.to_csv(res_file, sep=RESULTS_SEPARATOR, index=True)
        averages.to_csv(avg_file, sep=RESULTS_SEPARATOR, index=True)

    # Show results
    if meta['show_averages']:
        display(averages)
    if meta['show_confusion_matrices']:
        fig, axes = plt.subplot(2, 2, figsize=(15, 18))
        for confusion_matrix, clf, ax in zip(conf_matrices, classifiers, axes.flatten()):
            disp = ConfusionMatrixDisplay(confusion_matrix=confusion_matrix, display_labels=labels, ax=ax)
            disp.plot(cmap=plt.cm.Blues)
            ax.set_title(clf.__class__.__name__)
        fig.suptitle("Confusion Matrices")
        plt.tight_layout()
        plt.show()


def save_models(classifiers: dict[str, PMMLPipeline], meta: dict):
    for name, cls in classifiers.items():
        now = datetime.now()
        timestamp = now.strftime("%Y%m%d-%H%M%S")
        filename = f"{BASE_PATH}/{RESULTS_DIRECTORY}/{timestamp}_{name}_{meta['feature_selector']}f.pmml"
        sklearn2pmml(cls, filename, with_repr=True)
        print(f"Model {name} saved to {filename}")

#### Import labels

In [3]:
labels = pd.read_csv(f"{BASE_PATH}/{LABELS_FILENAME}", sep=LABELS_SEPARATOR, header=0, index_col=0).dropna()
labels.head()

                binary-stress  affect3-class
subject/task
2ea4_Breathing              0              0
2ea4_Counting1              1              2
2ea4_Counting2              1              2
2ea4_Counting3              1              2
2ea4_Math                   1              2

# Classical approaches

Several models are tested: Random Forests, K nearets neighbors, SVM, and Multi Layer Perceptron. All models are fitted 10 times on random splits, and the average scores over 10 repetitions are reported.

The dimensionality of the features matrix can be reduced using PCA or Feature selection. Feature selection is performed using L1 penalty or Recursive Feature Elimination (RFE). The optimal number of features is determined using RFECV.

#### Import and prepare dataset
We use handcrafted features.

In [4]:
X = pd.read_csv(f"{BASE_PATH}/{FEATURES_FILENAME}", sep=FEATURES_SEPARATOR, header=0, index_col=0)
display(X)
for col in X.columns:
    X[col] = X[col].astype(np.float32)
display(X)

,meanHR,minHR,maxHR,sdHR,modeHR,nNN,meanNN,SDSD,CVNN,SDNN,...,min_scl,mean_scl,sd_scl,nSCR,aucSCR,meanAmpSCR,maxAmpSCR,meanRespSCR,sumAmpSCR,sumRespSCR
2ea4_Baseline,63.430749,57.034221,79.575597,4.685361,22.541376,62.000000,950.677419,41.894327,64.816310,0.068179,...,-1.132743,0.022668,0.891539,10.000000,-302.978934,0.666899,1.475682,1.160000,6.668994,11.600000
2ea4_Breathing,61.712623,45.871560,84.033613,11.009485,38.162054,59.666667,1002.893855,106.620821,173.316789,0.172817,...,-0.968230,-0.006435,0.951185,7.333333,120.038332,0.651699,1.748524,1.126095,4.779126,7.882667
2ea4_Counting1,70.973286,58.479532,82.872928,5.448858,24.393396,69.000000,850.550725,42.532503,67.603176,0.079482,...,-2.159093,0.012778,0.827482,7.000000,-92.589522,0.860715,2.091642,2.433429,6.025006,17.034000
2ea4_Counting2,64.301095,56.285178,79.787234,5.497250,23.502056,63.000000,939.587302,58.386027,76.102820,0.080996,...,-1.167276,-0.011765,0.937448,6.000000,315.591734,0.543249,1.502306,1.810000,3.259493,10.860000
2ea4_Counting3,66.253079,55.762082,80.645161,5.443328,24.883080,65.000000,911.661538,42.884190,74.003384,0.081174,...,-1.494708,-0.015553,0.904099,12.000000,558.708830,0.721123,1.743292,1.282167,8.653481,15.386000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
y9z6_Reading,73.839596,54.545455,175.438596,19.184174,120.893142,70.000000,845.657143,141.770371,133.471012,0.157831,...,-1.017887,-0.000668,0.990734,2.400000,122.464218,0.197116,0.600114,13.550667,0.473079,32.521600
y9z6_Relax,58.768320,50.933786,75.000000,4.024016,24.066214,58.000000,1025.475862,73.275208,66.397765,0.064748,...,-2.730086,0.022081,0.680286,5.000000,205.591732,0.939958,1.721442,2.791200,4.699788,13.956000
y9z6_Speaking,79.574294,61.601643,176.470588,27.277891,114.868946,73.000000,810.684932,171.499251,168.914413,0.208360,...,-1.291715,-0.029019,0.932817,5.000000,608.317194,0.320072,0.772637,1.639200,1.600359,8.196000
y9z6_Stroop,64.712598,58.027079,73.710074,3.844910,15.682994,63.000000,930.412698,45.644284,54.586653,0.058669,...,-1.833577,0.002666,0.974272,3.103448,5.575997,0.310237,1.061803,3.314667,0.962805,10.286897
y9z6_Video1,60.061811,53.191489,75.757576,3.685925,22.566086,59.310345,1002.581395,59.116008,59.104060,0.058952,...,-1.142737,0.001318,0.998102,2.033898,-18.621149,0.110889,0.243203,6.086667,0.225537,9.284746

,meanHR,minHR,maxHR,sdHR,modeHR,nNN,meanNN,SDSD,CVNN,SDNN,...,min_scl,mean_scl,sd_scl,nSCR,aucSCR,meanAmpSCR,maxAmpSCR,meanRespSCR,sumAmpSCR,sumRespSCR
2ea4_Baseline,63.430748,57.034222,79.575600,4.685360,22.541376,62.000000,950.677429,41.894325,64.816307,0.068179,...,-1.132743,0.022668,0.891540,10.000000,-302.978943,0.666899,1.475682,1.160000,6.668994,11.600000
2ea4_Breathing,61.712624,45.871559,84.033615,11.009485,38.162052,59.666668,1002.893860,106.620819,173.316788,0.172817,...,-0.968230,-0.006435,0.951185,7.333333,120.038330,0.651699,1.748524,1.126095,4.779126,7.882667
2ea4_Counting1,70.973282,58.479530,82.872925,5.448858,24.393396,69.000000,850.550720,42.532505,67.603180,0.079482,...,-2.159093,0.012778,0.827482,7.000000,-92.589523,0.860715,2.091642,2.433429,6.025006,17.034000
2ea4_Counting2,64.301094,56.285179,79.787231,5.497250,23.502056,63.000000,939.587280,58.386028,76.102821,0.080996,...,-1.167276,-0.011765,0.937448,6.000000,315.591736,0.543249,1.502306,1.810000,3.259493,10.860000
2ea4_Counting3,66.253082,55.762081,80.645164,5.443328,24.883080,65.000000,911.661560,42.884190,74.003387,0.081174,...,-1.494708,-0.015553,0.904099,12.000000,558.708801,0.721123,1.743292,1.282167,8.653481,15.386000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
y9z6_Reading,73.839600,54.545456,175.438599,19.184174,120.893143,70.000000,845.657166,141.770370,133.471008,0.157831,...,-1.017887,-0.000668,0.990734,2.400000,122.464218,0.197116,0.600114,13.550667,0.473079,32.521599
y9z6_Relax,58.768322,50.933784,75.000000,4.024016,24.066214,58.000000,1025.475830,73.275208,66.397766,0.064748,...,-2.730086,0.022081,0.680286,5.000000,205.591736,0.939958,1.721442,2.791200,4.699788,13.956000
y9z6_Speaking,79.574295,61.601643,176.470581,27.277891,114.868942,73.000000,810.684937,171.499252,168.914413,0.208360,...,-1.291716,-0.029019,0.932817,5.000000,608.317200,0.320072,0.772637,1.639200,1.600359,8.196000
y9z6_Stroop,64.712601,58.027081,73.710075,3.844910,15.682995,63.000000,930.412720,45.644283,54.586655,0.058669,...,-1.833577,0.002666,0.974272,3.103448,5.575997,0.310237,1.061803,3.314667,0.962805,10.286897
y9z6_Video1,60.061813,53.191490,75.757576,3.685925,22.566086,59.310345,1002.581421,59.116009,59.104061,0.058952,...,-1.142737,0.001318,0.998102,2.033898,-18.621149,0.110889,0.243203,6.086667,0.225537,9.284746

In [5]:
# Selecting rows that actually have entries in "labels" file
idx = list(X.merge(labels, left_index= True, right_index=True).index)
labels = labels.loc[idx]
x = X.loc[idx]

### Parameter and models configuration

In [ ]:
# Hyperparameters tunning

from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import train_test_split
from scipy.stats import uniform

state_int = 21
y = labels["binary-stress"]
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, stratify=y, random_state=state_int
)

tunning_for = {
    "RandomForest": True,
    "KNN": True,
    "SVM": True,
    "MLP": True,
}

if tunning_for["RandomForest"]:
    print("Tunning RandomForestClassifier...")
    param_grid = {
        "n_estimators": [100, 200, 300, 350, 400, 450, 500],
        "max_depth": [None, 5, 10, 15, 20, 30, 40, 50],
        "min_samples_split": [2, 5, 10],
        "min_samples_leaf": [1, 2, 4],
        "max_features": ["sqrt", "log2", None],
        "bootstrap": [True, False],
    }
    random_search = RandomizedSearchCV(
        RandomForestClassifier(),
        param_grid,
        random_state=state_int,
    )
    random_search.fit(x_train, y_train)
    print(f"Best parameters found for RF: {random_search.best_params_}")
    print(f"Best score: {random_search.best_score_:.3f}")
    best_model = random_search.best_estimator_
    accuracy = best_model.score(x_test, y_test)
    print(f"Test set accuracy: {accuracy:.3f}")

if tunning_for["KNN"]:
    print("Tunning KNeighborsClassifier...")
    param_grid = {
        "n_neighbors": list(range(2, 21, 1)),
        "weights": ["uniform", "distance"],
        "p": [1, 2],
    }
    random_search = RandomizedSearchCV(
        KNeighborsClassifier(),
        param_grid,
        random_state=state_int
    )
    random_search.fit(x_train, y_train)
    print(f"Best parameters found for KNN: {random_search.best_params_}")
    print(f"Best score: {random_search.best_score_:.3f}")
    best_model = random_search.best_estimator_
    accuracy = best_model.score(x_test, y_test)
    print(f"Test set accuracy: {accuracy:.3f}")

if tunning_for["SVM"]:
    print("Tunning SVM...")
    param_grid = {
        "C": [0.1, 1, 10, 100, 1000],
        "gamma": ["auto", "scale"],
        "kernel": ["linear", "rbf",],
    }
    random_search = RandomizedSearchCV(
        SVC(),
        param_grid,
        random_state=state_int
    )
    random_search.fit(x_train, y_train)
    print(f"Best parameters found for SVM: {random_search.best_params_}")
    print(f"Best score: {random_search.best_score_:.3f}")
    best_model = random_search.best_estimator_
    accuracy = best_model.score(x_test, y_test)
    print(f"Test set accuracy: {accuracy:.3f}")

if tunning_for["MLP"]:
    print("Tunning MLP...")
    param_grid = {
        "hidden_layer_sizes": [(50,), (100,), (50,50,), (100,100), (50,50,50,), (100,100,50,50,)],
        "activation": ["tanh", "relu"],
        "learning_rate_init": uniform(0.0001, 0.01),
        'alpha': uniform(0.0001, 0.01),
    }
    random_search = RandomizedSearchCV(
        MLPClassifier(max_iter=1000),
        param_grid,
        random_state=state_int,
    )
    random_search.fit(x_train, y_train)
    print(f"Best parameters found for MLP: {random_search.best_params_}")
    print(f"Best score: {random_search.best_score_:.3f}")
    best_model = random_search.best_estimator_
    accuracy = best_model.score(x_test, y_test)
    print(f"Test set accuracy: {accuracy:.3f}")

raise Exception("Tunning finished. Please, set the best parameters found.")

Tunning RandomForestClassifier...
Best parameters found for RF: {'n_estimators': 500, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': 'log2', 'max_depth': 40, 'bootstrap': True}
Best score: 0.721
Test set accuracy: 0.714
Tunning KNeighborsClassifier...
Best parameters found for KNN: {'weights': 'distance', 'p': 2, 'n_neighbors': 11}
Best score: 0.589
Test set accuracy: 0.500
Tunning SVM...

In [ ]:
params = {
    "state_int": 21,
    "feature_selector": None,  ###  None, 'PCA', 'L1', or 'RFE' (ordered by speed)
    "test_size": 0.2,  # Paper value: 0.2
    "n_splits": 10,  # Paper value: 10
    "save_results": False,
    "show_averages": True,
    "show_confusion_matrices": True,
    "save_models": False,
}

list_classif = [RandomForestClassifier(
                        n_estimators=500,
                        min_samples_split=5,
                        min_samples_leaf=2,
                        max_features="log2",
                        max_depth=40,
                        bootstrap=True,
                        random_state=params['state_int']),
                KNeighborsClassifier(n_neighbors=11, weights="distance", p=2),
                SVC(gamma='auto', kernel='rbf', random_state=params['state_int']),
                MLPClassifier(max_iter=5000, random_state=params['state_int'], hidden_layer_sizes=[])
]

### Binary classification

In [ ]:
params['classification'] = 'binary'
params['classes'] = BIN_LABELS
y = labels['binary-stress']
show_label_stats(params['classes'], y)

res, conf, models = make_nclassif_random_splits(x, y,
                    n_splits = params['n_splits'],
                    feature_selector = params['feature_selector'],
                    list_classifiers = list_classif,
                    random_seed = params['state_int'],
                    test_size = params['test_size'],
                    )
output(res, conf, list_classif, params)
if params['save_models']:
    save_models(models, params)

In [ ]:
print('Standard Deviations over 10 splits:')
res.groupby(['classifier']).std()[['f1-score', 'accuracy', 'time']]

### Ternary classification

In [ ]:
params['classification'] = 'ternary'
params['classes'] = TER_LABELS
y = labels['affect3-class']
show_label_stats(params['classes'], y)

res, conf, models = make_nclassif_random_splits(x, y,
                    n_splits = params['n_splits'],
                    feature_selector = params['feature_selector'],
                    list_classifiers = list_classif,
                    random_seed = params['state_int'],
                    test_size = params['test_size'],
                    )
output(res, conf, list_classif, params)
if params["save_models"]:
    save_models(models, params)

In [ ]:
print('Standard Deviations over 10 splits:')
res.groupby(['classifier']).std()[['f1-score', 'accuracy', 'time']]