In [ ]:
%matplotlib widget
import pandas as pd
from IPython.display import display

BASE_DIR = "./Results_StdSubject_AllTasks/20251016_MinOvSamp"

BINARY = f"{BASE_DIR}/20251016-194311_binary_10s&0.2_RFEf.21.csv"
TERNARY = f"{BASE_DIR}/20251016-195254_ternary_10s&0.2_RFEf.21.csv"
QUATERNARY = f"{BASE_DIR}/20251016-201512_quaternary_10s&0.2_RFEf.21.csv"

In [2]:
pd_bin = pd.read_csv(BINARY, sep=";", index_col=0)
display(pd_bin.groupby(["classifier"]).mean()[["f1-score", "accuracy", "time"]])
display(pd_bin.groupby(["classifier"]).std()[["f1-score", "accuracy", "time"]])

pd_ter = pd.read_csv(TERNARY, sep=";", index_col=0)
display(pd_ter.groupby(["classifier"]).mean()[["f1-score", "accuracy", "time"]])
display(pd_ter.groupby(["classifier"]).std()[["f1-score", "accuracy", "time"]])

pd_qad = pd.read_csv(QUATERNARY, sep=";", index_col=0)
display(pd_qad.groupby(["classifier"]).mean()[["f1-score", "accuracy", "time"]])
display(pd_qad.groupby(["classifier"]).std()[["f1-score", "accuracy", "time"]])

                        f1-score  accuracy      time
classifier
KNeighborsClassifier    0.696839  0.696298  6.395409
MLPClassifier_HLs(100)  0.706362  0.705454  7.471604
RandomForestClassifier  0.747090  0.747906  7.566285
SVC                     0.694840  0.694307  6.822167

                        f1-score  accuracy      time
classifier
KNeighborsClassifier    0.037799  0.038784  0.594669
MLPClassifier_HLs(100)  0.025962  0.025593  1.015474
RandomForestClassifier  0.028520  0.026797  0.804900
SVC                     0.020053  0.021616  0.645514

                        f1-score  accuracy      time
classifier
KNeighborsClassifier    0.710454  0.700815  8.156003
MLPClassifier_HLs(100)  0.697720  0.688274  8.901008
RandomForestClassifier  0.709994  0.702337  9.246516
SVC                     0.699769  0.691291  8.271637

                        f1-score  accuracy      time
classifier
KNeighborsClassifier    0.040163  0.040351  0.985822
MLPClassifier_HLs(100)  0.027527  0.026572  1.107738
RandomForestClassifier  0.027963  0.027726  1.094098
SVC                     0.024669  0.024885  1.034388

                        f1-score  accuracy      time
classifier
KNeighborsClassifier    0.705313  0.702621  9.174502
MLPClassifier_HLs(100)  0.700288  0.696963  9.003410
RandomForestClassifier  0.656780  0.656395  9.656308
SVC                     0.715893  0.713664  9.023448

                        f1-score  accuracy      time
classifier
KNeighborsClassifier    0.043930  0.043915  1.032625
MLPClassifier_HLs(100)  0.027016  0.028373  0.796906
RandomForestClassifier  0.038207  0.036188  1.180944
SVC                     0.034495  0.033118  0.969672